/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface LobbyChatroomCard {
    id: bigint;
    topic: string;
    activeUserCount: bigint;
    lastActivity: bigint;
    createdAt: bigint;
    description: string;
    isLive: boolean;
    mediaUrl?: string;
    messageCount: bigint;
    mediaType?: string;
    category: string;
    pinnedVideoId?: bigint;
    presenceIndicator: bigint;
}
export interface UserProfile {
    name: string;
    presetAvatar?: string;
    anonId: string;
    avatarUrl?: string;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface ReplyPreview {
    messageId: bigint;
    sender: string;
    mediaThumbnail?: string;
    contentSnippet: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface MessageWithReactions {
    id: bigint;
    content: string;
    messageId: string;
    chatroomId: bigint;
    sender: string;
    mediaUrl?: string;
    reportReasons: Array<string>;
    avatarUrl?: string;
    replyToMessageId?: bigint;
    timestamp: bigint;
    mediaType?: string;
    reactions: List_1;
    senderId: string;
    flagCount: bigint;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export type List_1 = [Reaction, List_1] | null;
export interface Message {
    id: bigint;
    content: string;
    messageId: string;
    chatroomId: bigint;
    sender: string;
    mediaUrl?: string;
    reportReasons: Array<string>;
    avatarUrl?: string;
    replyToMessageId?: bigint;
    timestamp: bigint;
    mediaType?: string;
    senderId: string;
    flagCount: bigint;
}
export type List = [string, List] | null;
export interface ChatroomWithLiveStatus {
    id: bigint;
    topic: string;
    activeUserCount: bigint;
    lastActivity: bigint;
    createdAt: bigint;
    description: string;
    isLive: boolean;
    mediaUrl?: string;
    viewCount: bigint;
    messageCount: bigint;
    mediaType?: string;
    category: string;
    pinnedVideoId?: bigint;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface Reaction {
    count: bigint;
    emoji: string;
    users: List;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blob_hash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addReaction(messageId: bigint, emoji: string, userId: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cleanupInactiveUsers(): Promise<void>;
    createChatroom(topic: string, description: string, mediaUrl: string, mediaType: string, category: string): Promise<bigint>;
    deleteChatroomWithPassword(chatroomId: bigint, _password: string): Promise<void>;
    fetchGiphyResults(searchTerm: string): Promise<string>;
    fetchTrendingGiphyGifs(): Promise<string>;
    fetchTwitchThumbnail(channelName: string): Promise<string>;
    fetchTwitterOEmbed(tweetUrl: string): Promise<string>;
    fetchTwitterThumbnail(tweetUrl: string): Promise<string>;
    fetchYouTubeThumbnail(videoId: string): Promise<string>;
    filterChatroomsByCategory(category: string): Promise<Array<ChatroomWithLiveStatus>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChatroom(id: bigint): Promise<ChatroomWithLiveStatus | null>;
    getChatrooms(): Promise<Array<ChatroomWithLiveStatus>>;
    getFlaggedMessages(): Promise<Array<Message>>;
    getLobbyChatroomCards(): Promise<Array<LobbyChatroomCard>>;
    getMessageWithReactionsAndReplies(chatroomId: bigint): Promise<Array<MessageWithReactions>>;
    getMessages(chatroomId: bigint): Promise<Array<Message>>;
    getPinnedVideo(chatroomId: bigint): Promise<bigint | null>;
    getReactions(messageId: bigint): Promise<Array<Reaction>>;
    getReplies(chatroomId: bigint, parentMessageId: bigint): Promise<Array<Message>>;
    getReplyPreview(chatroomId: bigint, messageId: bigint): Promise<ReplyPreview | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    incrementViewCount(chatroomId: bigint, userId: string): Promise<void>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    pinVideo(chatroomId: bigint, messageId: bigint): Promise<void>;
    removeReaction(messageId: bigint, emoji: string, userId: string): Promise<void>;
    reportMessage(messageId: bigint, reason: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchChatrooms(searchTerm: string): Promise<Array<ChatroomWithLiveStatus>>;
    sendMessage(content: string, sender: string, chatroomId: bigint, mediaUrl: string | null, mediaType: string | null, avatarUrl: string | null, senderId: string, replyToMessageId: bigint | null): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    unpinVideo(chatroomId: bigint): Promise<void>;
    updateAvatarRetroactively(senderId: string, newAvatarUrl: string | null): Promise<void>;
    updateUsernameRetroactively(senderId: string, newUsername: string): Promise<void>;
}
import type { ChatroomWithLiveStatus as _ChatroomWithLiveStatus, List as _List, List_1 as _List_1, LobbyChatroomCard as _LobbyChatroomCard, Message as _Message, MessageWithReactions as _MessageWithReactions, Reaction as _Reaction, ReplyPreview as _ReplyPreview, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addReaction(arg0: bigint, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addReaction(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReaction(arg0, arg1, arg2);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cleanupInactiveUsers(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cleanupInactiveUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cleanupInactiveUsers();
            return result;
        }
    }
    async createChatroom(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createChatroom(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createChatroom(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async deleteChatroomWithPassword(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteChatroomWithPassword(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteChatroomWithPassword(arg0, arg1);
            return result;
        }
    }
    async fetchGiphyResults(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchGiphyResults(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchGiphyResults(arg0);
            return result;
        }
    }
    async fetchTrendingGiphyGifs(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchTrendingGiphyGifs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchTrendingGiphyGifs();
            return result;
        }
    }
    async fetchTwitchThumbnail(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchTwitchThumbnail(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchTwitchThumbnail(arg0);
            return result;
        }
    }
    async fetchTwitterOEmbed(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchTwitterOEmbed(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchTwitterOEmbed(arg0);
            return result;
        }
    }
    async fetchTwitterThumbnail(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchTwitterThumbnail(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchTwitterThumbnail(arg0);
            return result;
        }
    }
    async fetchYouTubeThumbnail(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchYouTubeThumbnail(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchYouTubeThumbnail(arg0);
            return result;
        }
    }
    async filterChatroomsByCategory(arg0: string): Promise<Array<ChatroomWithLiveStatus>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterChatroomsByCategory(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterChatroomsByCategory(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChatroom(arg0: bigint): Promise<ChatroomWithLiveStatus | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatroom(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatroom(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChatrooms(): Promise<Array<ChatroomWithLiveStatus>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatrooms();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatrooms();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFlaggedMessages(): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFlaggedMessages();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFlaggedMessages();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLobbyChatroomCards(): Promise<Array<LobbyChatroomCard>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLobbyChatroomCards();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLobbyChatroomCards();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessageWithReactionsAndReplies(arg0: bigint): Promise<Array<MessageWithReactions>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessageWithReactionsAndReplies(arg0);
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessageWithReactionsAndReplies(arg0);
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessages(arg0: bigint): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages(arg0);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages(arg0);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPinnedVideo(arg0: bigint): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPinnedVideo(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPinnedVideo(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReactions(arg0: bigint): Promise<Array<Reaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReactions(arg0);
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReactions(arg0);
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReplies(arg0: bigint, arg1: bigint): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReplies(arg0, arg1);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReplies(arg0, arg1);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReplyPreview(arg0: bigint, arg1: bigint): Promise<ReplyPreview | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getReplyPreview(arg0, arg1);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReplyPreview(arg0, arg1);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async incrementViewCount(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.incrementViewCount(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.incrementViewCount(arg0, arg1);
            return result;
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async pinVideo(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.pinVideo(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.pinVideo(arg0, arg1);
            return result;
        }
    }
    async removeReaction(arg0: bigint, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeReaction(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeReaction(arg0, arg1, arg2);
            return result;
        }
    }
    async reportMessage(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reportMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reportMessage(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n41(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n41(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchChatrooms(arg0: string): Promise<Array<ChatroomWithLiveStatus>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchChatrooms(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchChatrooms(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendMessage(arg0: string, arg1: string, arg2: bigint, arg3: string | null, arg4: string | null, arg5: string | null, arg6: string, arg7: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1, arg2, to_candid_opt_n43(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n43(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n43(this._uploadFile, this._downloadFile, arg5), arg6, to_candid_opt_n44(this._uploadFile, this._downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1, arg2, to_candid_opt_n43(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n43(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n43(this._uploadFile, this._downloadFile, arg5), arg6, to_candid_opt_n44(this._uploadFile, this._downloadFile, arg7));
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async unpinVideo(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unpinVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unpinVideo(arg0);
            return result;
        }
    }
    async updateAvatarRetroactively(arg0: string, arg1: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAvatarRetroactively(arg0, to_candid_opt_n43(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAvatarRetroactively(arg0, to_candid_opt_n43(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateUsernameRetroactively(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUsernameRetroactively(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUsernameRetroactively(arg0, arg1);
            return result;
        }
    }
}
function from_candid_ChatroomWithLiveStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChatroomWithLiveStatus): ChatroomWithLiveStatus {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_List_1_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _List_1): List_1 {
    return from_candid_opt_n30(_uploadFile, _downloadFile, value);
}
function from_candid_List_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _List): List {
    return from_candid_opt_n35(_uploadFile, _downloadFile, value);
}
function from_candid_LobbyChatroomCard_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LobbyChatroomCard): LobbyChatroomCard {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_MessageWithReactions_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MessageWithReactions): MessageWithReactions {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Message_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Message): Message {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Reaction_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Reaction): Reaction {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_ReplyPreview_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReplyPreview): ReplyPreview {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ChatroomWithLiveStatus]): ChatroomWithLiveStatus | null {
    return value.length === 0 ? null : from_candid_ChatroomWithLiveStatus_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [[_Reaction, _List_1]]): [Reaction, List_1] | null {
    return value.length === 0 ? null : from_candid_tuple_n31(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [[string, _List]]): [string, List] | null {
    return value.length === 0 ? null : from_candid_tuple_n36(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ReplyPreview]): ReplyPreview | null {
    return value.length === 0 ? null : from_candid_ReplyPreview_n39(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    topic: string;
    activeUserCount: bigint;
    lastActivity: bigint;
    createdAt: bigint;
    description: string;
    isLive: boolean;
    mediaUrl: [] | [string];
    viewCount: bigint;
    messageCount: bigint;
    mediaType: [] | [string];
    category: string;
    pinnedVideoId: [] | [bigint];
}): {
    id: bigint;
    topic: string;
    activeUserCount: bigint;
    lastActivity: bigint;
    createdAt: bigint;
    description: string;
    isLive: boolean;
    mediaUrl?: string;
    viewCount: bigint;
    messageCount: bigint;
    mediaType?: string;
    category: string;
    pinnedVideoId?: bigint;
} {
    return {
        id: value.id,
        topic: value.topic,
        activeUserCount: value.activeUserCount,
        lastActivity: value.lastActivity,
        createdAt: value.createdAt,
        description: value.description,
        isLive: value.isLive,
        mediaUrl: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.mediaUrl)),
        viewCount: value.viewCount,
        messageCount: value.messageCount,
        mediaType: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.mediaType)),
        category: value.category,
        pinnedVideoId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.pinnedVideoId))
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    presetAvatar: [] | [string];
    anonId: string;
    avatarUrl: [] | [string];
}): {
    name: string;
    presetAvatar?: string;
    anonId: string;
    avatarUrl?: string;
} {
    return {
        name: value.name,
        presetAvatar: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.presetAvatar)),
        anonId: value.anonId,
        avatarUrl: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.avatarUrl))
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    content: string;
    messageId: string;
    chatroomId: bigint;
    sender: string;
    mediaUrl: [] | [string];
    reportReasons: Array<string>;
    avatarUrl: [] | [string];
    replyToMessageId: [] | [bigint];
    timestamp: bigint;
    mediaType: [] | [string];
    senderId: string;
    flagCount: bigint;
}): {
    id: bigint;
    content: string;
    messageId: string;
    chatroomId: bigint;
    sender: string;
    mediaUrl?: string;
    reportReasons: Array<string>;
    avatarUrl?: string;
    replyToMessageId?: bigint;
    timestamp: bigint;
    mediaType?: string;
    senderId: string;
    flagCount: bigint;
} {
    return {
        id: value.id,
        content: value.content,
        messageId: value.messageId,
        chatroomId: value.chatroomId,
        sender: value.sender,
        mediaUrl: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.mediaUrl)),
        reportReasons: value.reportReasons,
        avatarUrl: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.avatarUrl)),
        replyToMessageId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.replyToMessageId)),
        timestamp: value.timestamp,
        mediaType: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.mediaType)),
        senderId: value.senderId,
        flagCount: value.flagCount
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    topic: string;
    activeUserCount: bigint;
    lastActivity: bigint;
    createdAt: bigint;
    description: string;
    isLive: boolean;
    mediaUrl: [] | [string];
    messageCount: bigint;
    mediaType: [] | [string];
    category: string;
    pinnedVideoId: [] | [bigint];
    presenceIndicator: bigint;
}): {
    id: bigint;
    topic: string;
    activeUserCount: bigint;
    lastActivity: bigint;
    createdAt: bigint;
    description: string;
    isLive: boolean;
    mediaUrl?: string;
    messageCount: bigint;
    mediaType?: string;
    category: string;
    pinnedVideoId?: bigint;
    presenceIndicator: bigint;
} {
    return {
        id: value.id,
        topic: value.topic,
        activeUserCount: value.activeUserCount,
        lastActivity: value.lastActivity,
        createdAt: value.createdAt,
        description: value.description,
        isLive: value.isLive,
        mediaUrl: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.mediaUrl)),
        messageCount: value.messageCount,
        mediaType: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.mediaType)),
        category: value.category,
        pinnedVideoId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.pinnedVideoId)),
        presenceIndicator: value.presenceIndicator
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    content: string;
    messageId: string;
    chatroomId: bigint;
    sender: string;
    mediaUrl: [] | [string];
    reportReasons: Array<string>;
    avatarUrl: [] | [string];
    replyToMessageId: [] | [bigint];
    timestamp: bigint;
    mediaType: [] | [string];
    reactions: _List_1;
    senderId: string;
    flagCount: bigint;
}): {
    id: bigint;
    content: string;
    messageId: string;
    chatroomId: bigint;
    sender: string;
    mediaUrl?: string;
    reportReasons: Array<string>;
    avatarUrl?: string;
    replyToMessageId?: bigint;
    timestamp: bigint;
    mediaType?: string;
    reactions: List_1;
    senderId: string;
    flagCount: bigint;
} {
    return {
        id: value.id,
        content: value.content,
        messageId: value.messageId,
        chatroomId: value.chatroomId,
        sender: value.sender,
        mediaUrl: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.mediaUrl)),
        reportReasons: value.reportReasons,
        avatarUrl: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.avatarUrl)),
        replyToMessageId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.replyToMessageId)),
        timestamp: value.timestamp,
        mediaType: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.mediaType)),
        reactions: from_candid_List_1_n29(_uploadFile, _downloadFile, value.reactions),
        senderId: value.senderId,
        flagCount: value.flagCount
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    count: bigint;
    emoji: string;
    users: _List;
}): {
    count: bigint;
    emoji: string;
    users: List;
} {
    return {
        count: value.count,
        emoji: value.emoji,
        users: from_candid_List_n34(_uploadFile, _downloadFile, value.users)
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    messageId: bigint;
    sender: string;
    mediaThumbnail: [] | [string];
    contentSnippet: string;
}): {
    messageId: bigint;
    sender: string;
    mediaThumbnail?: string;
    contentSnippet: string;
} {
    return {
        messageId: value.messageId,
        sender: value.sender,
        mediaThumbnail: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.mediaThumbnail)),
        contentSnippet: value.contentSnippet
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_tuple_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_Reaction, _List_1]): [Reaction, List_1] {
    return [
        from_candid_Reaction_n32(_uploadFile, _downloadFile, value[0]),
        from_candid_List_1_n29(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, _List]): [string, List] {
    return [
        value[0],
        from_candid_List_n34(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChatroomWithLiveStatus>): Array<ChatroomWithLiveStatus> {
    return value.map((x)=>from_candid_ChatroomWithLiveStatus_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Message>): Array<Message> {
    return value.map((x)=>from_candid_Message_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LobbyChatroomCard>): Array<LobbyChatroomCard> {
    return value.map((x)=>from_candid_LobbyChatroomCard_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MessageWithReactions>): Array<MessageWithReactions> {
    return value.map((x)=>from_candid_MessageWithReactions_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Reaction>): Array<Reaction> {
    return value.map((x)=>from_candid_Reaction_n32(_uploadFile, _downloadFile, x));
}
function to_candid_UserProfile_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n42(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    presetAvatar?: string;
    anonId: string;
    avatarUrl?: string;
}): {
    name: string;
    presetAvatar: [] | [string];
    anonId: string;
    avatarUrl: [] | [string];
} {
    return {
        name: value.name,
        presetAvatar: value.presetAvatar ? candid_some(value.presetAvatar) : candid_none(),
        anonId: value.anonId,
        avatarUrl: value.avatarUrl ? candid_some(value.avatarUrl) : candid_none()
    };
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
