/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const List = IDL.Rec();
export const List_1 = IDL.Rec();
export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ChatroomWithLiveStatus = IDL.Record({
  'id' : IDL.Nat,
  'topic' : IDL.Text,
  'activeUserCount' : IDL.Nat,
  'lastActivity' : IDL.Int,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'isLive' : IDL.Bool,
  'mediaUrl' : IDL.Opt(IDL.Text),
  'viewCount' : IDL.Nat,
  'messageCount' : IDL.Nat,
  'mediaType' : IDL.Opt(IDL.Text),
  'category' : IDL.Text,
  'pinnedVideoId' : IDL.Opt(IDL.Nat),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'presetAvatar' : IDL.Opt(IDL.Text),
  'anonId' : IDL.Text,
  'avatarUrl' : IDL.Opt(IDL.Text),
});
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'messageId' : IDL.Text,
  'chatroomId' : IDL.Nat,
  'sender' : IDL.Text,
  'mediaUrl' : IDL.Opt(IDL.Text),
  'reportReasons' : IDL.Vec(IDL.Text),
  'avatarUrl' : IDL.Opt(IDL.Text),
  'replyToMessageId' : IDL.Opt(IDL.Nat),
  'timestamp' : IDL.Int,
  'mediaType' : IDL.Opt(IDL.Text),
  'senderId' : IDL.Text,
  'flagCount' : IDL.Nat,
});
export const LobbyChatroomCard = IDL.Record({
  'id' : IDL.Nat,
  'topic' : IDL.Text,
  'activeUserCount' : IDL.Nat,
  'lastActivity' : IDL.Int,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'isLive' : IDL.Bool,
  'mediaUrl' : IDL.Opt(IDL.Text),
  'messageCount' : IDL.Nat,
  'mediaType' : IDL.Opt(IDL.Text),
  'category' : IDL.Text,
  'pinnedVideoId' : IDL.Opt(IDL.Nat),
  'presenceIndicator' : IDL.Nat,
});
List.fill(IDL.Opt(IDL.Tuple(IDL.Text, List)));
export const Reaction = IDL.Record({
  'count' : IDL.Nat,
  'emoji' : IDL.Text,
  'users' : List,
});
List_1.fill(IDL.Opt(IDL.Tuple(Reaction, List_1)));
export const MessageWithReactions = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'messageId' : IDL.Text,
  'chatroomId' : IDL.Nat,
  'sender' : IDL.Text,
  'mediaUrl' : IDL.Opt(IDL.Text),
  'reportReasons' : IDL.Vec(IDL.Text),
  'avatarUrl' : IDL.Opt(IDL.Text),
  'replyToMessageId' : IDL.Opt(IDL.Nat),
  'timestamp' : IDL.Int,
  'mediaType' : IDL.Opt(IDL.Text),
  'reactions' : List_1,
  'senderId' : IDL.Text,
  'flagCount' : IDL.Nat,
});
export const ReplyPreview = IDL.Record({
  'messageId' : IDL.Nat,
  'sender' : IDL.Text,
  'mediaThumbnail' : IDL.Opt(IDL.Text),
  'contentSnippet' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addReaction' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cleanupInactiveUsers' : IDL.Func([], [], []),
  'createChatroom' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteChatroomWithPassword' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'fetchGiphyResults' : IDL.Func([IDL.Text], [IDL.Text], []),
  'fetchTrendingGiphyGifs' : IDL.Func([], [IDL.Text], []),
  'fetchTwitchThumbnail' : IDL.Func([IDL.Text], [IDL.Text], []),
  'fetchTwitterOEmbed' : IDL.Func([IDL.Text], [IDL.Text], []),
  'fetchTwitterThumbnail' : IDL.Func([IDL.Text], [IDL.Text], []),
  'fetchYouTubeThumbnail' : IDL.Func([IDL.Text], [IDL.Text], []),
  'filterChatroomsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ChatroomWithLiveStatus)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChatroom' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(ChatroomWithLiveStatus)],
      ['query'],
    ),
  'getChatrooms' : IDL.Func([], [IDL.Vec(ChatroomWithLiveStatus)], ['query']),
  'getFlaggedMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getLobbyChatroomCards' : IDL.Func(
      [],
      [IDL.Vec(LobbyChatroomCard)],
      ['query'],
    ),
  'getMessageWithReactionsAndReplies' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(MessageWithReactions)],
      ['query'],
    ),
  'getMessages' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
  'getPinnedVideo' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Nat)], ['query']),
  'getReactions' : IDL.Func([IDL.Nat], [IDL.Vec(Reaction)], ['query']),
  'getReplies' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Message)], ['query']),
  'getReplyPreview' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Opt(ReplyPreview)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'incrementViewCount' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'pinVideo' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'removeReaction' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'reportMessage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchChatrooms' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ChatroomWithLiveStatus)],
      ['query'],
    ),
  'sendMessage' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Opt(IDL.Nat),
      ],
      [],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'unpinVideo' : IDL.Func([IDL.Nat], [], []),
  'updateAvatarRetroactively' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
  'updateUsernameRetroactively' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const List = IDL.Rec();
  const List_1 = IDL.Rec();
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ChatroomWithLiveStatus = IDL.Record({
    'id' : IDL.Nat,
    'topic' : IDL.Text,
    'activeUserCount' : IDL.Nat,
    'lastActivity' : IDL.Int,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'isLive' : IDL.Bool,
    'mediaUrl' : IDL.Opt(IDL.Text),
    'viewCount' : IDL.Nat,
    'messageCount' : IDL.Nat,
    'mediaType' : IDL.Opt(IDL.Text),
    'category' : IDL.Text,
    'pinnedVideoId' : IDL.Opt(IDL.Nat),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'presetAvatar' : IDL.Opt(IDL.Text),
    'anonId' : IDL.Text,
    'avatarUrl' : IDL.Opt(IDL.Text),
  });
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'messageId' : IDL.Text,
    'chatroomId' : IDL.Nat,
    'sender' : IDL.Text,
    'mediaUrl' : IDL.Opt(IDL.Text),
    'reportReasons' : IDL.Vec(IDL.Text),
    'avatarUrl' : IDL.Opt(IDL.Text),
    'replyToMessageId' : IDL.Opt(IDL.Nat),
    'timestamp' : IDL.Int,
    'mediaType' : IDL.Opt(IDL.Text),
    'senderId' : IDL.Text,
    'flagCount' : IDL.Nat,
  });
  const LobbyChatroomCard = IDL.Record({
    'id' : IDL.Nat,
    'topic' : IDL.Text,
    'activeUserCount' : IDL.Nat,
    'lastActivity' : IDL.Int,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'isLive' : IDL.Bool,
    'mediaUrl' : IDL.Opt(IDL.Text),
    'messageCount' : IDL.Nat,
    'mediaType' : IDL.Opt(IDL.Text),
    'category' : IDL.Text,
    'pinnedVideoId' : IDL.Opt(IDL.Nat),
    'presenceIndicator' : IDL.Nat,
  });
  List.fill(IDL.Opt(IDL.Tuple(IDL.Text, List)));
  const Reaction = IDL.Record({
    'count' : IDL.Nat,
    'emoji' : IDL.Text,
    'users' : List,
  });
  List_1.fill(IDL.Opt(IDL.Tuple(Reaction, List_1)));
  const MessageWithReactions = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'messageId' : IDL.Text,
    'chatroomId' : IDL.Nat,
    'sender' : IDL.Text,
    'mediaUrl' : IDL.Opt(IDL.Text),
    'reportReasons' : IDL.Vec(IDL.Text),
    'avatarUrl' : IDL.Opt(IDL.Text),
    'replyToMessageId' : IDL.Opt(IDL.Nat),
    'timestamp' : IDL.Int,
    'mediaType' : IDL.Opt(IDL.Text),
    'reactions' : List_1,
    'senderId' : IDL.Text,
    'flagCount' : IDL.Nat,
  });
  const ReplyPreview = IDL.Record({
    'messageId' : IDL.Nat,
    'sender' : IDL.Text,
    'mediaThumbnail' : IDL.Opt(IDL.Text),
    'contentSnippet' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addReaction' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cleanupInactiveUsers' : IDL.Func([], [], []),
    'createChatroom' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteChatroomWithPassword' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'fetchGiphyResults' : IDL.Func([IDL.Text], [IDL.Text], []),
    'fetchTrendingGiphyGifs' : IDL.Func([], [IDL.Text], []),
    'fetchTwitchThumbnail' : IDL.Func([IDL.Text], [IDL.Text], []),
    'fetchTwitterOEmbed' : IDL.Func([IDL.Text], [IDL.Text], []),
    'fetchTwitterThumbnail' : IDL.Func([IDL.Text], [IDL.Text], []),
    'fetchYouTubeThumbnail' : IDL.Func([IDL.Text], [IDL.Text], []),
    'filterChatroomsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ChatroomWithLiveStatus)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChatroom' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(ChatroomWithLiveStatus)],
        ['query'],
      ),
    'getChatrooms' : IDL.Func([], [IDL.Vec(ChatroomWithLiveStatus)], ['query']),
    'getFlaggedMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getLobbyChatroomCards' : IDL.Func(
        [],
        [IDL.Vec(LobbyChatroomCard)],
        ['query'],
      ),
    'getMessageWithReactionsAndReplies' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(MessageWithReactions)],
        ['query'],
      ),
    'getMessages' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
    'getPinnedVideo' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Nat)], ['query']),
    'getReactions' : IDL.Func([IDL.Nat], [IDL.Vec(Reaction)], ['query']),
    'getReplies' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Message)], ['query']),
    'getReplyPreview' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Opt(ReplyPreview)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'incrementViewCount' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'pinVideo' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'removeReaction' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'reportMessage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchChatrooms' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ChatroomWithLiveStatus)],
        ['query'],
      ),
    'sendMessage' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Opt(IDL.Nat),
        ],
        [],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'unpinVideo' : IDL.Func([IDL.Nat], [], []),
    'updateAvatarRetroactively' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'updateUsernameRetroactively' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };