/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatroomWithLiveStatus {
  'id' : bigint,
  'topic' : string,
  'activeUserCount' : bigint,
  'lastActivity' : bigint,
  'createdAt' : bigint,
  'description' : string,
  'isLive' : boolean,
  'mediaUrl' : [] | [string],
  'viewCount' : bigint,
  'messageCount' : bigint,
  'mediaType' : [] | [string],
  'category' : string,
  'pinnedVideoId' : [] | [bigint],
}
export type List = [] | [[string, List]];
export type List_1 = [] | [[Reaction, List_1]];
export interface LobbyChatroomCard {
  'id' : bigint,
  'topic' : string,
  'activeUserCount' : bigint,
  'lastActivity' : bigint,
  'createdAt' : bigint,
  'description' : string,
  'isLive' : boolean,
  'mediaUrl' : [] | [string],
  'messageCount' : bigint,
  'mediaType' : [] | [string],
  'category' : string,
  'pinnedVideoId' : [] | [bigint],
  'presenceIndicator' : bigint,
}
export interface Message {
  'id' : bigint,
  'content' : string,
  'messageId' : string,
  'chatroomId' : bigint,
  'sender' : string,
  'mediaUrl' : [] | [string],
  'reportReasons' : Array<string>,
  'avatarUrl' : [] | [string],
  'replyToMessageId' : [] | [bigint],
  'timestamp' : bigint,
  'mediaType' : [] | [string],
  'senderId' : string,
  'flagCount' : bigint,
}
export interface MessageWithReactions {
  'id' : bigint,
  'content' : string,
  'messageId' : string,
  'chatroomId' : bigint,
  'sender' : string,
  'mediaUrl' : [] | [string],
  'reportReasons' : Array<string>,
  'avatarUrl' : [] | [string],
  'replyToMessageId' : [] | [bigint],
  'timestamp' : bigint,
  'mediaType' : [] | [string],
  'reactions' : List_1,
  'senderId' : string,
  'flagCount' : bigint,
}
export interface Reaction { 'count' : bigint, 'emoji' : string, 'users' : List }
export interface ReplyPreview {
  'messageId' : bigint,
  'sender' : string,
  'mediaThumbnail' : [] | [string],
  'contentSnippet' : string,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'name' : string,
  'presetAvatar' : [] | [string],
  'anonId' : string,
  'avatarUrl' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addReaction' : ActorMethod<[bigint, string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cleanupInactiveUsers' : ActorMethod<[], undefined>,
  'createChatroom' : ActorMethod<
    [string, string, string, string, string],
    bigint
  >,
  'deleteChatroomWithPassword' : ActorMethod<[bigint, string], undefined>,
  'fetchGiphyResults' : ActorMethod<[string], string>,
  'fetchTrendingGiphyGifs' : ActorMethod<[], string>,
  'fetchTwitchThumbnail' : ActorMethod<[string], string>,
  'fetchTwitterOEmbed' : ActorMethod<[string], string>,
  'fetchTwitterThumbnail' : ActorMethod<[string], string>,
  'fetchYouTubeThumbnail' : ActorMethod<[string], string>,
  'filterChatroomsByCategory' : ActorMethod<
    [string],
    Array<ChatroomWithLiveStatus>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChatroom' : ActorMethod<[bigint], [] | [ChatroomWithLiveStatus]>,
  'getChatrooms' : ActorMethod<[], Array<ChatroomWithLiveStatus>>,
  'getFlaggedMessages' : ActorMethod<[], Array<Message>>,
  'getLobbyChatroomCards' : ActorMethod<[], Array<LobbyChatroomCard>>,
  'getMessageWithReactionsAndReplies' : ActorMethod<
    [bigint],
    Array<MessageWithReactions>
  >,
  'getMessages' : ActorMethod<[bigint], Array<Message>>,
  'getPinnedVideo' : ActorMethod<[bigint], [] | [bigint]>,
  'getReactions' : ActorMethod<[bigint], Array<Reaction>>,
  'getReplies' : ActorMethod<[bigint, bigint], Array<Message>>,
  'getReplyPreview' : ActorMethod<[bigint, bigint], [] | [ReplyPreview]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'incrementViewCount' : ActorMethod<[bigint, string], undefined>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'pinVideo' : ActorMethod<[bigint, bigint], undefined>,
  'removeReaction' : ActorMethod<[bigint, string, string], undefined>,
  'reportMessage' : ActorMethod<[bigint, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchChatrooms' : ActorMethod<[string], Array<ChatroomWithLiveStatus>>,
  'sendMessage' : ActorMethod<
    [
      string,
      string,
      bigint,
      [] | [string],
      [] | [string],
      [] | [string],
      string,
      [] | [bigint],
    ],
    undefined
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'unpinVideo' : ActorMethod<[bigint], undefined>,
  'updateAvatarRetroactively' : ActorMethod<[string, [] | [string]], undefined>,
  'updateUsernameRetroactively' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];